services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampledb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
        - "3306:3306"
